### ISSUE TITLE
GC segfaults with asyncnet

### ISSUE THREAD

**Issue by def-** [Araq/Nim#1796]
I'm using this little program:

```nim
import asyncnet, asyncdispatch

const text =  """HTTP/1.1 200 OK
Date: Mon, 23 May 2005 22:38:34 GMT
Server: Apache/1.3.3.7 (Unix) (Red-Hat/Linux)
Last-Modified: Wed, 08 Jan 2003 23:11:55 GMT
ETag: "3f80f-1b6-3e1cb03b"
Content-Type: text/html; charset=UTF-8
Content-Length: 131
Accept-Ranges: bytes
Connection: close

<html>
<head>
  <title>An Example Page</title>
</head>
<body>
  Hello World, this is a very simple HTML document.
</body>
</html>"""

proc processClient(client: AsyncSocket) {.async.} =
  let line = await client.recvLine()
  await client.send(text)
  client.close()

proc serve() {.async.} =
  var server = newAsyncSocket()
  server.setSockOpt(OptReuseAddr, true)
  server.bindAddr(Port(8000))
  server.listen()

  while true:
    let client = await server.accept()

    asyncCheck processClient(client)

asyncCheck serve()
runForever()
```

Then I'm using wrk to simulate a lot of accesses to it with `wrk -t1 -c 1 -d 30s http://127.0.0.1:8000/`.

In release mode (not in debug) the GC segfaults (boehm works):
```
Program received signal SIGSEGV, Segmentation fault.
0x0000000000411531 in collectwhite_64804 ()
(gdb) bt
#0  0x0000000000411531 in collectwhite_64804 ()
#1  0x0000000000408215 in TMP137 ()
#2  0x00000000004115be in collectwhite_64804 ()
#3  0x0000000000403055 in TMP125 ()
#4  0x00000000004115be in collectwhite_64804 ()
#5  0x0000000000413cee in collectroots_67201 ()
#6  0x000000000041478e in collectcycles_67245 ()
#7  0x0000000000414aa0 in collectctbody_71619 ()
#8  0x000000000041665e in copyString ()
#9  0x0000000000408e23 in readintoiter_169440 ()
#10 0x0000000000408ca7 in cb_170219 ()
#11 0x00000000004053ad in cb_162806 ()
#12 0x0000000000406b36 in runforever_167239 ()
#13 0x000000000041bcdd in NimMain ()
#14 0x0000000000400ffd in main ()
```

**Comment by Araq** [comment]
This is a much simpler test program to reproduce the same problem: 

```nimrod

type
  Node = ref object
    a, b: Node
    leaf: string

proc createCycle(leaf: string): Node =
  new result
  result.a = result
  shallowCopy result.leaf, leaf

proc main =
  for i in 0 .. 100_000:
    var leaf = "this is the leaf. it allocates"
    let x = createCycle(leaf)
    let y = createCycle(leaf)
  echo "done"

main()
```

**Comment by def-** [comment]
@Araq: That doesn't crash for me.

**Comment by Araq** [comment]
That's only because of a missing assertion.

**Comment by dom96** [comment]
:+1:
