### ISSUE TITLE
[Codegen] wrong JS code

### ISSUE THREAD

**Issue by yglukhov** [Araq/Nim#2581]
```nim
const someVars = [ "Hello" ]

proc getSomeVar: string =
    for i in someVars:
        if i == "Hello":
            result = i
            break

echo getSomeVar()
```
```sh
$ nim js --lineTrace:off --stackTrace:off -d:nodejs ~/test.nim
$ node ~/nimcache/test.js

/Users/yglukhov/nimcache/test.js:69
    var len = s_9314.length-1;
                    ^
TypeError: Cannot read property 'length' of null
    at toJSStr (/Users/yglukhov/nimcache/test.js:69:21)
    at rawEcho (/Users/yglukhov/nimcache/test.js:115:16)
    at Object.<anonymous> (/Users/yglukhov/nimcache/test.js:271:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

**Comment by yglukhov** [comment]
One more example. I don't know if it's the same issue, but here it is anyway:
```nim
const someVars = [ "Hello" ]

proc getSomeVar: string =
    result = "Bye"
    for i, j in someVars:
        if i == 0:
            return j

echo getSomeVar()
```
```sh
$ nim js --lineTrace:off --stackTrace:off -d:nodejs ~/test.nim
$ node ~/nimcache/test.js
# Empty output. Expected: "Hello"
```
