### ISSUE TITLE
JS Codegen. Passing arguments by var in certain cases leads to invalid JS.

### ISSUE THREAD

**Issue by yglukhov** [Araq/Nim#2798]
```nim
import intsets

type T = object
    iSet: IntSet

var t: T
t.iSet = initIntSet()
t.iSet.incl(123)
```
Runtime error:
```
/Users/yglukhov/nimcache/test.js:480
if (!!((t_28665.data_28040[chckIndx(h_28668, 0, t_28665.data_28040.length)-0] 
                                                                  ^
TypeError: Cannot read property 'length' of undefined
    at intsetput_28662 (/Users/yglukhov/nimcache/test.js:480:67)
    at incl_28832 (/Users/yglukhov/nimcache/test.js:527:15)
    at Object.<anonymous> (/Users/yglukhov/nimcache/test.js:534:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```
Related JS function:
```js
function incl_28832(s_28835, key_28836) {
// not interesting
}
```
Related JS call:
```js
incl_28832(t_30004[0], "iset_30003", 123);
```

**Comment by ozra** [comment]
I still wonder why __emsciptem__ is not favored for JS-gen?

**Comment by yglukhov** [comment]
I may miss something, but I would never trade "native" JS backend for emscripten. It produces readable JS code, and it may benefit from knowing Nim's semantics. It is also a lot more lightweight. Yes, there's a use-case when you want to use an existing cpp lib in JS, but that just doesn't sound right to me.
